version: '3'

services:
  backend:
    build: ./backend/JokeApi
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
